name: on_time
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  dio: ^5.5.0+1
  dartz: ^0.10.1
  sqflite: ^2.3.2
  intl: ^0.19.0
  go_router: ^14.2.3
  bloc: ^8.1.4
  meta: ^1.15.0
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
